version: '3.8'

services:
  web:
    build:
      context: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/comps
    environment:
      - PYTHONUNBUFFERED=1
