FROM python=3.11.8-bookworm

ENV PYTHONUNBUFFERED 1

# Creating root directory for our project in the container
RUN mkdir -p /comps

# Setting the working directory to /comps
WORKDIR /comps

# Copying the current directory contents into the container at /comps
COPY . /comps/

# Installing needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Binding a port
# EXPOSE 8000

# Command to run the app
ENTRYPOINT ["python", "manage.py"]
CMD ["runserver", "0.0.0.0:8000"]


COPY ./ports.conf /etc/apache2/ports.conf
COPY ./apache.conf /etc/apache2/sites-available/000-default.conf
