# Generated by Django 5.0.2 on 2024-06-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0002_alter_competition_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
